/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.dobavljac;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.util.FrmModovi;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.kontroler.KontrolerKlijent;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Dobavljac;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Grad;

/**
 *
 * @author milos
 */
public class FrmDobavljac extends javax.swing.JPanel {

    FrmDobavljaciPrikaz tabela;
    Dobavljac dobavljac;
    int mod;

    /**
     * Creates new form FrmDobavljac
     */
    public FrmDobavljac(FrmDobavljaciPrikaz tabela, Dobavljac dobavljac, int mod) throws Exception {
        initComponents();

        this.tabela = tabela;
        this.dobavljac = dobavljac;
        this.mod = mod;

        prikaziGradove();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        cmbGradovi = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ime:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Prezime:");

        cmbGradovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Grad:");

        btnDodaj.setText("Dodaj Dobavljaca");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni Dobavljaca");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi Dobavljaca");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDodaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnIzmeni)
                        .addGap(47, 47, 47)
                        .addComponent(btnObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(cmbGradovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Dobavljac dobavljac = new Dobavljac();

        if (txtIme.getText().isEmpty() || txtIme.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti ime za dobavljaca!", "Dodavanje dobavljaca", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtPrezime.getText().isEmpty() || txtPrezime.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti prezime za dobavljaca!", "Dodavanje dobavljaca", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cmbGradovi.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati neki od gradova!", "Dodavanje dobavljaca", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dobavljac.setIme(txtIme.getText().trim());
        dobavljac.setPrezime(txtPrezime.getText().trim());
        dobavljac.setGrad((Grad) cmbGradovi.getSelectedItem());

        try {
            KontrolerKlijent.vratiInstancu().dodajDobavljaca(dobavljac);
            JOptionPane.showMessageDialog(this, "Dobavljac dodat!\nGenerisani ID: " + dobavljac.getId(), "Dodavanje Dobavljaca", JOptionPane.INFORMATION_MESSAGE);
            int izbor = JOptionPane.showConfirmDialog(this, "Da li zelite da nastavite sa dodavanjem dobavljaca?", "Dodavanje Dobavljaca", JOptionPane.YES_NO_OPTION);
            if (izbor == JOptionPane.YES_OPTION) {
                txtIme.setText("");
                txtPrezime.setText("");
                cmbGradovi.setSelectedIndex(-1);
            } else {
                this.getTopLevelAncestor().setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dobavljac nije dodat!\n" + e.getMessage(), "Dodavanje Dobavljaca", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (dobavljac == null) {
            JOptionPane.showMessageDialog(this, "Dobavljac nije ucitan!", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int izbor = JOptionPane.showConfirmDialog(this, "Da li ste zaista sigurni da zelite da izbrisete Dobavljaca:\n" + dobavljac, "Brisanje Dobavljaca", JOptionPane.YES_NO_OPTION);
        if (izbor == JOptionPane.YES_OPTION) {
            try {
                KontrolerKlijent.vratiInstancu().obrisiDobavljaca(dobavljac);
                JOptionPane.showMessageDialog(this, "Uspesno ste izbrisali Dobavljaca:\n" + dobavljac, "Brisanje Dobavljaca", JOptionPane.INFORMATION_MESSAGE);
                this.getTopLevelAncestor().setVisible(false);
                tabela.prikaziDobavljace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (dobavljac == null) {
            JOptionPane.showMessageDialog(this, "Dobavljac nije ucitan!", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dobavljac.setGrad((Grad) cmbGradovi.getSelectedItem());
        try {
            KontrolerKlijent.vratiInstancu().izmeniDobavljaca(dobavljac);
            JOptionPane.showMessageDialog(this, "Uspesno ste izmenili Dobavljaca:\n" + dobavljac, "Izmena Dobavljaca", JOptionPane.INFORMATION_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);
            tabela.prikaziDobavljace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JComboBox cmbGradovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void prikaziGradove() throws Exception {
        List<Grad> gradovi = KontrolerKlijent.vratiInstancu().prikaziSveGradove();
        cmbGradovi.removeAllItems();
        cmbGradovi.setModel(new DefaultComboBoxModel(gradovi.toArray()));
        cmbGradovi.setSelectedIndex(-1);
    }

    private void pripremiFormu() {
        if (mod == FrmModovi.FORMA_MOD_DODAVANJE) {
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);
        }
        if (mod == FrmModovi.FORMA_MOD_IZMENA) {
            txtIme.setText(dobavljac.getIme());
            txtPrezime.setText(dobavljac.getPrezime());
            cmbGradovi.setSelectedItem(dobavljac.getGrad());

            txtIme.setEditable(false);
            txtPrezime.setEditable(false);

            btnDodaj.setVisible(false);
            btnObrisi.setVisible(false);
        }
        if (mod == FrmModovi.FORMA_MOD_CITANJE) {
            txtIme.setText(dobavljac.getIme());
            txtPrezime.setText(dobavljac.getPrezime());
            cmbGradovi.setSelectedItem(dobavljac.getGrad());

            txtIme.setEditable(false);
            txtPrezime.setEditable(false);
            cmbGradovi.setEnabled(false);

            btnDodaj.setVisible(false);
            btnIzmeni.setVisible(false);
        }
    }
}
