/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.lek;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.util.FrmModovi;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.kontroler.KontrolerKlijent;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.tabele.model.ModelLekovi;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Lek;

/**
 *
 * @author milos
 */
public class FrmLekoviPrikaz extends javax.swing.JPanel {

    /**
     * Creates new form FrmLekoviPrikaz
     */
    public FrmLekoviPrikaz() {
        initComponents();

        prikaziLekove();
    }

    public JTextField getTxtPretraga() {
        return txtPretraga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        btnPonistiPretragu = new javax.swing.JButton();
        btnIzmena = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLekovi = new javax.swing.JTable();
        btnSastavLeka = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Naziv:");

        btnPretraga.setText("PRETRAGA");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnPonistiPretragu.setText("Ponisti pretragu");
        btnPonistiPretragu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiPretraguActionPerformed(evt);
            }
        });

        btnIzmena.setText("IZMENA");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        btnBrisanje.setText("BRISANJE");

        tblLekovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLekovi);

        btnSastavLeka.setText("Prikazi sastav leka");
        btnSastavLeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSastavLekaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(491, 491, 491)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBrisanje)
                                .addComponent(btnIzmena)
                                .addComponent(btnSastavLeka)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnPretraga)
                                    .addGap(52, 52, 52)
                                    .addComponent(btnPonistiPretragu)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnIzmena)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraga)
                    .addComponent(btnPonistiPretragu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrisanje)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnSastavLeka)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPonistiPretraguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiPretraguActionPerformed
        txtPretraga.setText("");
        try {
            prikaziLekove();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPonistiPretraguActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
//        if (txtPretraga.getText().isEmpty() || txtPretraga.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Morate uneti parametar za pretragu!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
        String kriterijum = txtPretraga.getText().trim();
        try {
            prikaziPretraguLekova(kriterijum);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnSastavLekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSastavLekaActionPerformed
        int red = tblLekovi.getSelectedRow();
        ModelLekovi model = (ModelLekovi) tblLekovi.getModel();
        if (red >= 0) {
            Lek lek = model.getLek(red);
            JOptionPane.showMessageDialog(this, "Lek: " + lek + " se sastoji od:\n" + lek.getSastav(), "SASTAV", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neki od lekova!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSastavLekaActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
        int red = tblLekovi.getSelectedRow();
        ModelLekovi model = (ModelLekovi) tblLekovi.getModel();
        if (red >= 0) {
            Lek lek = model.getLek(red);
            JDialog dijalog = new JDialog((JFrame) null, "Lek", true);
            try {
                JPanel panel = new FrmLek(this, lek, FrmModovi.FORMA_MOD_IZMENA);
                dijalog.add(panel);
                dijalog.pack();
                dijalog.setLocationRelativeTo(null);
                dijalog.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neki od lekova!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnPonistiPretragu;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnSastavLeka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLekovi;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void prikaziLekove() {
        ModelLekovi model = new ModelLekovi(new ArrayList<>());
        tblLekovi.setModel(model);
    }

    private void prikaziPretraguLekova(String kriterijum) throws Exception {
        List<Lek> lekovi = KontrolerKlijent.vratiInstancu().pretragaLekova(kriterijum);
        tblLekovi.setModel(new ModelLekovi(lekovi));
    }
}
