/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.lek;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.util.FrmModovi;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.kontroler.KontrolerKlijent;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.tabele.model.ModelSupstance;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Lek;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Supstanca;

/**
 *
 * @author milos
 */
public class FrmLek extends javax.swing.JPanel {

    List<Supstanca> supstanceZaLek;
    FrmLekoviPrikaz tabela;
    Lek lek;
    int mod;

    /**
     * Creates new form FrmLek
     */
    public FrmLek(FrmLekoviPrikaz tabela, Lek lek, int mod) throws Exception {
        initComponents();

        this.tabela = tabela;
        this.lek = lek;
        this.mod = mod;
        this.supstanceZaLek = new ArrayList<>();

        prikaziSupstance();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSerijskiBroj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoziranje = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDostupneSupstance = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupstanceZaLek = new javax.swing.JTable();
        btnDodajSupstancu = new javax.swing.JButton();
        btnUkloniSupstancu = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Serijski broj:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Naziv:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Doziranje:");

        btnDodaj.setText("Dodaj Lek");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni Lek");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi Lek");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblDostupneSupstance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDostupneSupstance);

        tblSupstanceZaLek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSupstanceZaLek);

        btnDodajSupstancu.setText("Dodaj >>");
        btnDodajSupstancu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajSupstancuActionPerformed(evt);
            }
        });

        btnUkloniSupstancu.setText("<< Ukloni");
        btnUkloniSupstancu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniSupstancuActionPerformed(evt);
            }
        });

        lblInfo.setText("Izaberite supstance koje su potrebne za pravljenje leka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSerijskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtNaziv)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajSupstancu)
                    .addComponent(btnUkloniSupstancu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnDodaj)
                .addGap(132, 132, 132)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisi)
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDoziranje, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSerijskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDoziranje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDodajSupstancu)
                        .addGap(50, 50, 50)
                        .addComponent(btnUkloniSupstancu)
                        .addGap(95, 95, 95)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajSupstancuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajSupstancuActionPerformed
        int red = tblDostupneSupstance.getSelectedRow();
        ModelSupstance modelDostupne = (ModelSupstance) tblDostupneSupstance.getModel();
        if (red >= 0) {
            Supstanca supstanca = modelDostupne.getSupstanca(red);
            String unosKolicine = JOptionPane.showInputDialog(this, "Unesite zeljenu kolicinu supstance " + supstanca);
            long unetaKolicina = Long.parseLong(unosKolicine);
            if (unetaKolicina <= 0 || unetaKolicina > supstanca.getKolicinaZaliha()) {
                JOptionPane.showMessageDialog(this, "Uneta kolicina mora biti izmedju 1 i trenutne kolicine zaliha!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            supstanca.setKolicinaZaliha(supstanca.getKolicinaZaliha() - unetaKolicina);

            Supstanca postojeca = supstanceZaLek.stream()
                    .filter(s -> s.getSifra().equals(supstanca.getSifra()))
                    .findFirst()
                    .orElse(null);

            if (postojeca != null) {
                postojeca.setKolicinaZaliha(postojeca.getKolicinaZaliha() + unetaKolicina);
            } else {
                Supstanca supstancaZaLek = new Supstanca();
                supstancaZaLek.setSifra(supstanca.getSifra());
                supstancaZaLek.setNaziv(supstanca.getNaziv());
                supstancaZaLek.setCena(supstanca.getCena());
                supstancaZaLek.setKolicinaZaliha(unetaKolicina);

                supstanceZaLek.add(supstancaZaLek);
            }

            ModelSupstance modelZaLek = new ModelSupstance(supstanceZaLek);
            tblSupstanceZaLek.setModel(modelZaLek);

            ModelSupstance azuriraniModelSupstance = new ModelSupstance(modelDostupne.getSupstance());
            tblDostupneSupstance.setModel(azuriraniModelSupstance);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neku od supstanci!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajSupstancuActionPerformed

    private void btnUkloniSupstancuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniSupstancuActionPerformed
        int red = tblSupstanceZaLek.getSelectedRow();
        ModelSupstance modelDostupne = (ModelSupstance) tblDostupneSupstance.getModel();
        if (red >= 0) {
            Supstanca supstancaZaLek = supstanceZaLek.get(red);

            modelDostupne.getSupstance().stream()
                    .filter(s -> s.getSifra().equals(supstancaZaLek.getSifra()))
                    .findFirst()
                    .ifPresent(s -> s.setKolicinaZaliha(s.getKolicinaZaliha() + supstancaZaLek.getKolicinaZaliha()));

            supstanceZaLek.remove(red);

            ModelSupstance modelZaLek = new ModelSupstance(supstanceZaLek);
            tblSupstanceZaLek.setModel(modelZaLek);

            ModelSupstance azuriraniModelSupstance = new ModelSupstance(modelDostupne.getSupstance());
            tblDostupneSupstance.setModel(azuriraniModelSupstance);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neku od supstanci!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUkloniSupstancuActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (txtSerijskiBroj.getText().isEmpty() || txtSerijskiBroj.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti serijski broj leka!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (txtNaziv.getText().isEmpty() || txtNaziv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv leka!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (txtDoziranje.getText().isEmpty() || txtDoziranje.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti doziranje leka!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ModelSupstance model = (ModelSupstance) tblSupstanceZaLek.getModel();
        if (model.getSupstance() == null || model.getSupstance().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti bar 1 supstancu za lek!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            String sBroj = txtSerijskiBroj.getText().trim();

            if (sBroj.startsWith("0")) {
                JOptionPane.showMessageDialog(this, "Uneti serijski broj ne sme zapoceti sa nulom!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Long serijskiBroj = Long.valueOf(sBroj);
            String naziv = txtNaziv.getText().trim();
            String doziranje = txtDoziranje.getText().trim();
            List<Supstanca> supstanceZaLek = model.getSupstance();
            Lek lek = new Lek(serijskiBroj, naziv, doziranje, supstanceZaLek);

            KontrolerKlijent.vratiInstancu().dodajLek(lek);
            JOptionPane.showMessageDialog(this, "Sistem je sacuvao lek!\n" + lek, "Dodavanje Leka", JOptionPane.INFORMATION_MESSAGE);
            int izbor = JOptionPane.showConfirmDialog(this, "Da li zelite da nastavite sa dodavanjem lekova?", "Dodavanje Leka", JOptionPane.YES_NO_OPTION);
            if (izbor == JOptionPane.YES_OPTION) {
                txtSerijskiBroj.setText("");
                txtNaziv.setText("");
                txtDoziranje.setText("");
                for (int i = 0; i < supstanceZaLek.size(); i++) {
                    supstanceZaLek.remove(i);
                }
                tblSupstanceZaLek.setModel(new ModelSupstance(supstanceZaLek));
            } else {
                this.getTopLevelAncestor().setVisible(false);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Uneti serijski broj mora biti broj!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva lek", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            System.out.println("Greska " + e.getMessage());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (lek == null) {
            JOptionPane.showMessageDialog(this, "Lek nije ucitan!", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDoziranje.getText().trim().isEmpty() || txtDoziranje.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti tekst za novo doziranje!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        lek.setDoziranje(txtDoziranje.getText().trim());
        try {
            KontrolerKlijent.vratiInstancu().izmeniLek(lek);
            JOptionPane.showMessageDialog(this, "Sistem je sacuvao lek:\n" + lek, "Izmena Leka", JOptionPane.INFORMATION_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);
            tabela.prikaziLekove();
            tabela.getTxtPretraga().setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva lek", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            System.out.println("Greska " + e.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (lek == null) {
            JOptionPane.showMessageDialog(this, "Lek nije ucitan!", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int izbor = JOptionPane.showConfirmDialog(this, "Da li ste zaista sigurni da zelite da izbrisete Lek:\n" + lek, "Brisanje Leka", JOptionPane.YES_NO_OPTION);
        if (izbor == JOptionPane.YES_OPTION) {
            try {
                KontrolerKlijent.vratiInstancu().obrisiLek(lek);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao lek:\n" + lek, "Brisanje Leka", JOptionPane.INFORMATION_MESSAGE);
                this.getTopLevelAncestor().setVisible(false);
                tabela.prikaziLekove();
                tabela.getTxtPretraga().setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise lek", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
                System.out.println("Greska " + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise lek", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajSupstancu;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUkloniSupstancu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tblDostupneSupstance;
    private javax.swing.JTable tblSupstanceZaLek;
    private javax.swing.JTextField txtDoziranje;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSerijskiBroj;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        if (mod == FrmModovi.FORMA_MOD_DODAVANJE) {
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);
        }
        if (mod == FrmModovi.FORMA_MOD_IZMENA) {
            txtSerijskiBroj.setText(lek.getSerijskiBroj().toString());
            txtNaziv.setText(lek.getNaziv());
            txtDoziranje.setText(lek.getDoziranje());
            tblDostupneSupstance.setModel(new ModelSupstance(lek.getSastav()));

            txtSerijskiBroj.setEditable(false);
            txtNaziv.setEditable(false);
            jScrollPane2.setVisible(false);
            lblInfo.setVisible(false);

            btnDodaj.setVisible(false);
            btnObrisi.setVisible(false);
            btnDodajSupstancu.setVisible(false);
            btnUkloniSupstancu.setVisible(false);
        }
        if (mod == FrmModovi.FORMA_MOD_CITANJE) {
            txtSerijskiBroj.setText(lek.getSerijskiBroj().toString());
            txtNaziv.setText(lek.getNaziv());
            txtDoziranje.setText(lek.getDoziranje());
            tblDostupneSupstance.setModel(new ModelSupstance(lek.getSastav()));

            txtSerijskiBroj.setEditable(false);
            txtNaziv.setEditable(false);
            txtDoziranje.setEditable(false);
            jScrollPane2.setVisible(false);
            lblInfo.setVisible(false);

            btnDodaj.setVisible(false);
            btnIzmeni.setVisible(false);
            btnDodajSupstancu.setVisible(false);
            btnUkloniSupstancu.setVisible(false);
        }
    }

    private void prikaziSupstance() throws Exception {
        List<Supstanca> supstance = KontrolerKlijent.vratiInstancu().prikaziSveSupstance();
        ModelSupstance modelDostupne = new ModelSupstance(supstance);
        tblDostupneSupstance.setModel(modelDostupne);

        ModelSupstance modelZaLek = new ModelSupstance(new ArrayList<>());
        tblSupstanceZaLek.setModel(modelZaLek);
    }
}
