/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.narudzbenica;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.kontroler.KontrolerKlijent;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.tabele.model.ModelStavkeNarudzbenice;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Dobavljac;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Korisnik;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Narudzbenica;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.StavkaNarudzbenice;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Supstanca;

/**
 *
 * @author milos
 */
public class FrmNarudzbenica extends javax.swing.JPanel {

    Korisnik korisnik;
    Narudzbenica narudzbenica;
    List<StavkaNarudzbenice> stavkeNarudzbenice;

    /**
     * Creates new form FrmNarudzbenica
     */
    public FrmNarudzbenica(Korisnik korisnik) throws Exception {
        initComponents();

        this.korisnik = korisnik;
        this.narudzbenica = new Narudzbenica();
        this.stavkeNarudzbenice = new ArrayList<>();

        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbDobavljaci = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnDodajNarudzbenicu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbSupstance = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        txtPodaciSupstance = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Datum:");

        txtDatum.setEditable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Dobavljac:");

        cmbDobavljaci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnDodajNarudzbenicu.setText("Dodaj narudzbenicu");
        btnDodajNarudzbenicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNarudzbenicuActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Supstanca:");

        cmbSupstance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSupstance.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSupstanceItemStateChanged(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ukupan iznos:");

        txtUkupanIznos.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sifra:");

        txtPodaciSupstance.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajNarudzbenicu)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnDodajStavku))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPodaciSupstance, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(cmbSupstance, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtSifra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDobavljaci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSupstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDobavljaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPodaciSupstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodajNarudzbenicu)
                            .addComponent(jLabel4)
                            .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSupstanceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSupstanceItemStateChanged
        if (cmbSupstance.getSelectedItem() != null) {
            txtPodaciSupstance.setText(((Supstanca) cmbSupstance.getSelectedItem()).toStringZaliheCena());
        }
    }//GEN-LAST:event_cmbSupstanceItemStateChanged

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        if (cmbSupstance.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati neku Supstancu!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Supstanca supstanca = (Supstanca) cmbSupstance.getSelectedItem();

        String unetaKolicina = JOptionPane.showInputDialog(this, "Unesite kolicinu supstance " + cmbSupstance.getSelectedItem() + " koju zelite da narucite:");
        long kolicinaPoruceneSupstance = Long.parseLong(unetaKolicina);

        if (kolicinaPoruceneSupstance <= 0) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu koja je veca od nule!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        StavkaNarudzbenice postojeca = null;

        for (StavkaNarudzbenice sn : stavkeNarudzbenice) {
            if (sn.getSupstanca().getSifra().equals(supstanca.getSifra())) {
                postojeca = sn;
                break;
            }
        }

        if (postojeca != null) {
            long novaKolicina = postojeca.getKolicinaSupstance() + kolicinaPoruceneSupstance;
            postojeca.setKolicinaSupstance(novaKolicina);
            postojeca.setIznosStavke(novaKolicina * supstanca.getCena());
        } else {
            StavkaNarudzbenice nova = new StavkaNarudzbenice();
            nova.setSupstanca(supstanca);
            nova.setKolicinaSupstance(kolicinaPoruceneSupstance);
            nova.setIznosStavke(kolicinaPoruceneSupstance * supstanca.getCena());

            if (stavkeNarudzbenice.isEmpty()) {
                nova.setRedniBroj(1L);
            } else {
                nova.setRedniBroj(stavkeNarudzbenice.size() + 1L);
            }

            stavkeNarudzbenice.add(nova);
        }

        long ukupanIznos = 0;

        for (StavkaNarudzbenice stavkaNarudzbenice : stavkeNarudzbenice) {
            ukupanIznos += stavkaNarudzbenice.getIznosStavke();
        }

        txtUkupanIznos.setText(String.valueOf(ukupanIznos));

        tblStavke.setModel(new ModelStavkeNarudzbenice(stavkeNarudzbenice));
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnDodajNarudzbenicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNarudzbenicuActionPerformed
        if (txtSifra.getText().trim().equals("") || txtSifra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti sifru Narudzbenice!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (cmbDobavljaci.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nekog Dobavljaca!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (stavkeNarudzbenice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti barem 1 stavku narudzbenice klikom na dugme Dodaj stavku!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Narudzbenica narudzbenica = new Narudzbenica();
        narudzbenica.setSifra(Long.valueOf(txtSifra.getText().trim()));

        String datumTekst = txtDatum.getText();
        DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
        LocalDate datum = LocalDate.parse(datumTekst, formater);
        narudzbenica.setDatum(datum);

        narudzbenica.setUkupanIznos(Long.valueOf(txtUkupanIznos.getText()));
        narudzbenica.setKorisnik(korisnik);
        narudzbenica.setDobavljac((Dobavljac) cmbDobavljaci.getSelectedItem());
        narudzbenica.setListaStavki(stavkeNarudzbenice);

        for (StavkaNarudzbenice stavkaNarudzbenice : stavkeNarudzbenice) {
            stavkaNarudzbenice.setNarudzbenica(narudzbenica);
        }

        try {
            KontrolerKlijent.vratiInstancu().dodajNarudzbenicu(narudzbenica);
            JOptionPane.showMessageDialog(this, "Uspesno ste dodali narudzbenicu:\n" + narudzbenica + " sa stavkama:\n" + stavkeNarudzbenice);
            int izbor = JOptionPane.showConfirmDialog(this, "Da li zelite da nastavite sa dodavanjem narudzbenica?", "Dodavanje Narudzbenice", JOptionPane.YES_NO_OPTION);
            if (izbor == JOptionPane.YES_OPTION) {
                txtSifra.setText("");
                cmbSupstance.setModel(new DefaultComboBoxModel(KontrolerKlijent.vratiInstancu().prikaziSveSupstance().toArray()));
                cmbSupstance.setSelectedIndex(-1);
                txtPodaciSupstance.setText("");
                cmbDobavljaci.setSelectedIndex(-1);
                stavkeNarudzbenice = new ArrayList<>();
                tblStavke.setModel(new ModelStavkeNarudzbenice(stavkeNarudzbenice));
                txtUkupanIznos.setText("");
            } else {
                this.getTopLevelAncestor().setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske\n" + e.getMessage(), "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajNarudzbenicuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNarudzbenicu;
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JComboBox cmbDobavljaci;
    private javax.swing.JComboBox cmbSupstance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtPodaciSupstance;
    private javax.swing.JTextField txtSifra;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() throws Exception {
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd.MM.YYYY.");
        String danasnjiDatum = LocalDate.now().format(format);
        txtDatum.setText(danasnjiDatum);

        cmbDobavljaci.removeAllItems();
        cmbDobavljaci.setModel(new DefaultComboBoxModel(KontrolerKlijent.vratiInstancu().prikaziSveDobavljace().toArray()));
        cmbDobavljaci.setSelectedIndex(-1);

        cmbSupstance.removeAllItems();
        cmbSupstance.setModel(new DefaultComboBoxModel(KontrolerKlijent.vratiInstancu().prikaziSveSupstance().toArray()));
        cmbSupstance.setSelectedIndex(-1);

        tblStavke.setModel(new ModelStavkeNarudzbenice(new ArrayList<>()));
    }
}
