/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.farmaceutska_industrija_klijent.forme.narudzbenica;

import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.kontroler.KontrolerKlijent;
import rs.ac.bg.fon.farmaceutska_industrija_klijent.tabele.model.ModelNarudzbenice;
import rs.ac.bg.fon.farmaceutska_industrija_zajednicki.domenske_klase.Narudzbenica;

/**
 *
 * @author milos
 */
public class FrmNarudzbenicePrikaz extends javax.swing.JPanel {

    /**
     * Creates new form FrmNarudzbenicePrikaz
     */
    public FrmNarudzbenicePrikaz() throws Exception {
        initComponents();

        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        prikaziNarudzbenice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNarudzbenice = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnPrikaziStavke = new javax.swing.JButton();

        tblNarudzbenice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNarudzbenice);

        btnObrisi.setText("Obrisi narudzbenicu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPrikaziStavke.setText("Prikazi stavke narudzbenice");
        btnPrikaziStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnPrikaziStavke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnObrisi)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziStavke)
                    .addComponent(btnObrisi))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkeActionPerformed
        int red = tblNarudzbenice.getSelectedRow();
        ModelNarudzbenice model = (ModelNarudzbenice) tblNarudzbenice.getModel();
        if (red >= 0) {
            Narudzbenica narudzbenica = model.getNarudzbenica(red);
            JOptionPane.showMessageDialog(this, "Narudzbenica: " + narudzbenica + "\nSadrzi stavke:\nNaruceno: " + narudzbenica.getListaStavki(), "Podaci o narudzbenici", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neku od narudzbenica!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkeActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = tblNarudzbenice.getSelectedRow();
        ModelNarudzbenice model = (ModelNarudzbenice) tblNarudzbenice.getModel();
        if (red >= 0) {
            Narudzbenica narudzbenica = model.getNarudzbenica(red);
            int izbor = JOptionPane.showConfirmDialog(this, "Da li ste zaista sigurni da zelite da izbrisete Narudzbenicu:\n" + narudzbenica, "Brisanje Narudzbenice", JOptionPane.YES_NO_OPTION);
            if (izbor == JOptionPane.YES_OPTION) {
                try {
                    KontrolerKlijent.vratiInstancu().obrisiNarudzbenicu(narudzbenica);
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao narudzbenicu:\n" + narudzbenica, "Brisanje Narudzbenice", JOptionPane.INFORMATION_MESSAGE);
                    prikaziNarudzbenice();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise narudzbenicu", "GRESKA!!!", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Greska " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati neku od narudzbenica!", "GRESKA!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPrikaziStavke;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNarudzbenice;
    // End of variables declaration//GEN-END:variables

    private void prikaziNarudzbenice() throws Exception {
        List<Narudzbenica> narudzbenice = KontrolerKlijent.vratiInstancu().prikaziSveNarudzbenice();
        tblNarudzbenice.setModel(new ModelNarudzbenice(narudzbenice));
    }
}
